env:
  goal_state_reward: 20
  item_state_reward: 10
  goal_no_item_penalty: -1
  time_penalty: -1
  with_animation: False
agent:
trainer:
  with_log: False
  with_validation: False
  with_visualization: False
  log_reward_step: 100
  